language: node_js
node_js: 
  - "10.16.0"
script: 
  - npm i
  - npm run build
deploy:
  provider: firebase
  token:
    secure: CT8E3KuZwy7227S5zncTamV9u1U2+VygAjwcqvnzZZLK3AWc7dsWkqZ7PB3BWKysw6HlcCKAHpN+hxY2wYgkILv74NDBzwJPDKRXpxXlm/lL/dBgq2c0LS61qa6KCJ9AfKZPMXRG9cju4n6VtPpVwjor1685lETBwM8qnyoJvKf9hLq12E7OHty6cQu8ODE2BoLW2vvREgBOnO2IIPVBNDAruNlNUDOsL9HuFLvi+RyDSUongZQ+akPJtb2F8mAbK2Y2HbvVXBCfR+bX0fD95xSNBYt5JmuCqu6e/NTI2gZ6IFBb+yayLMecZUsgKIn+iAO5+Sgbar2Uzim0fM8JzUkdm5wReBI58nWXG/cYivAVQRBcE5jvRcwatL2UBYjgOFiAwxprfYQXU6CZr965pllSjkt065Tbmi/BJfoTrwysavptdyhBjvgH5ZnQAXaW1egFt4uiDEu1rerq0uRW8OTpJCImWvNUxqgynSUqojlzN4gKYXdI/2oLjTrfkXfoTfJjBE19jrWwIrEnEJfQItOkEupTgF+mS3Ej/JbuZGBlMQ7hPGesUuqvALs5GHdp6hJF3nfYPInqy96rZ/NkJX1CdyVOxQKt6+5xiV2aWO4CLH1tnKsubKZQI61GcaTTxKbKL/laFdhKpL2+34ppIr5D7nHNYk8+lUxrNGSufC0=
  message: "first try at diploying a CI with firebase"
env:
  global:
    secure: CT8E3KuZwy7227S5zncTamV9u1U2+VygAjwcqvnzZZLK3AWc7dsWkqZ7PB3BWKysw6HlcCKAHpN+hxY2wYgkILv74NDBzwJPDKRXpxXlm/lL/dBgq2c0LS61qa6KCJ9AfKZPMXRG9cju4n6VtPpVwjor1685lETBwM8qnyoJvKf9hLq12E7OHty6cQu8ODE2BoLW2vvREgBOnO2IIPVBNDAruNlNUDOsL9HuFLvi+RyDSUongZQ+akPJtb2F8mAbK2Y2HbvVXBCfR+bX0fD95xSNBYt5JmuCqu6e/NTI2gZ6IFBb+yayLMecZUsgKIn+iAO5+Sgbar2Uzim0fM8JzUkdm5wReBI58nWXG/cYivAVQRBcE5jvRcwatL2UBYjgOFiAwxprfYQXU6CZr965pllSjkt065Tbmi/BJfoTrwysavptdyhBjvgH5ZnQAXaW1egFt4uiDEu1rerq0uRW8OTpJCImWvNUxqgynSUqojlzN4gKYXdI/2oLjTrfkXfoTfJjBE19jrWwIrEnEJfQItOkEupTgF+mS3Ej/JbuZGBlMQ7hPGesUuqvALs5GHdp6hJF3nfYPInqy96rZ/NkJX1CdyVOxQKt6+5xiV2aWO4CLH1tnKsubKZQI61GcaTTxKbKL/laFdhKpL2+34ppIr5D7nHNYk8+lUxrNGSufC0=
